# Generated by Django 4.1.5 on 2023-01-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify_Email_OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_verify_email', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=7, null=True)),
                ('gen_datetime', models.DateTimeField(auto_now_add=True)),
                ('exp_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
