# Generated by Django 4.1.5 on 2023-01-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_verify_email_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
