# Generated by Django 4.1.5 on 2023-01-30 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_area', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='take_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('proposal_seat', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('is_confirm_by_user', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('from_location', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='RiderFromLocation', related_query_name='RiderFromLocationQuery', to='App.location')),
                ('rider_user', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TakerUser', related_query_name='TakerUserQuery', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='RiderToLocation', related_query_name='RiderToLocationQuery', to='App.location')),
                ('vehical_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='proposal_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('vehical_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], default='Bike', max_length=50)),
                ('vehical_number', models.CharField(max_length=50)),
                ('seat_availability', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('booked_seat', models.IntegerField()),
                ('is_cancel', models.BooleanField(default=False)),
                ('from_location', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='UserFromLocation', related_query_name='UserFromLocationQUery', to='App.location')),
                ('proposal_user', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PorposalUser', related_query_name='PorposalUserQuery', to=settings.AUTH_USER_MODEL)),
                ('rider_details', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, null=True, related_name='RiderUser', related_query_name='RiderUserQuery', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='UserToLocation', related_query_name='UserToLocationQUery', to='App.location')),
            ],
        ),
    ]
