# Generated by Django 4.1.5 on 2023-01-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_proposal_trip_booked_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal_trip',
            name='booked_seat',
        ),
        migrations.RemoveField(
            model_name='proposal_trip',
            name='rider_details',
        ),
        migrations.RemoveField(
            model_name='take_trip',
            name='is_cancel',
        ),
        migrations.RemoveField(
            model_name='take_trip',
            name='is_confirm_by_user',
        ),
        migrations.RemoveField(
            model_name='take_trip',
            name='vehical_owner',
        ),
    ]
