# Generated by Django 4.1.5 on 2023-01-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_proposal_trip_booked_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='take_trip',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
